// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock_service

import (
	context "context"

	booking "github.com/iandanarko/concert/internal/model/booking"

	mock "github.com/stretchr/testify/mock"
)

// BookRepo is an autogenerated mock type for the BookRepo type
type BookRepo struct {
	mock.Mock
}

type BookRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *BookRepo) EXPECT() *BookRepo_Expecter {
	return &BookRepo_Expecter{mock: &_m.Mock}
}

// Book provides a mock function with given fields: ctx, spec
func (_m *BookRepo) Book(ctx context.Context, spec booking.BookSpec) error {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Book")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, booking.BookSpec) error); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookRepo_Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Book'
type BookRepo_Book_Call struct {
	*mock.Call
}

// Book is a helper method to define mock.On call
//   - ctx context.Context
//   - spec booking.BookSpec
func (_e *BookRepo_Expecter) Book(ctx interface{}, spec interface{}) *BookRepo_Book_Call {
	return &BookRepo_Book_Call{Call: _e.mock.On("Book", ctx, spec)}
}

func (_c *BookRepo_Book_Call) Run(run func(ctx context.Context, spec booking.BookSpec)) *BookRepo_Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(booking.BookSpec))
	})
	return _c
}

func (_c *BookRepo_Book_Call) Return(_a0 error) *BookRepo_Book_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookRepo_Book_Call) RunAndReturn(run func(context.Context, booking.BookSpec) error) *BookRepo_Book_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookRepo creates a new instance of BookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepo {
	mock := &BookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
