// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock_service

import mock "github.com/stretchr/testify/mock"

// GetAvailableConcertListUseCase is an autogenerated mock type for the GetAvailableConcertListUseCase type
type GetAvailableConcertListUseCase struct {
	mock.Mock
}

type GetAvailableConcertListUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAvailableConcertListUseCase) EXPECT() *GetAvailableConcertListUseCase_Expecter {
	return &GetAvailableConcertListUseCase_Expecter{mock: &_m.Mock}
}

// NewGetAvailableConcertListUseCase creates a new instance of GetAvailableConcertListUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAvailableConcertListUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAvailableConcertListUseCase {
	mock := &GetAvailableConcertListUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
