// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock_service

import (
	context "context"

	concert "github.com/iandanarko/concert/internal/model/concert"

	mock "github.com/stretchr/testify/mock"
)

// GetAvailableConcertListRepo is an autogenerated mock type for the GetAvailableConcertListRepo type
type GetAvailableConcertListRepo struct {
	mock.Mock
}

type GetAvailableConcertListRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *GetAvailableConcertListRepo) EXPECT() *GetAvailableConcertListRepo_Expecter {
	return &GetAvailableConcertListRepo_Expecter{mock: &_m.Mock}
}

// GetAvailableConcerts provides a mock function with given fields: ctx, spec
func (_m *GetAvailableConcertListRepo) GetAvailableConcerts(ctx context.Context, spec concert.GetAvailableSpec) ([]concert.Concert, uint64, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableConcerts")
	}

	var r0 []concert.Concert
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, concert.GetAvailableSpec) ([]concert.Concert, uint64, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, concert.GetAvailableSpec) []concert.Concert); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]concert.Concert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, concert.GetAvailableSpec) uint64); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, concert.GetAvailableSpec) error); ok {
		r2 = rf(ctx, spec)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAvailableConcertListRepo_GetAvailableConcerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableConcerts'
type GetAvailableConcertListRepo_GetAvailableConcerts_Call struct {
	*mock.Call
}

// GetAvailableConcerts is a helper method to define mock.On call
//   - ctx context.Context
//   - spec concert.GetAvailableSpec
func (_e *GetAvailableConcertListRepo_Expecter) GetAvailableConcerts(ctx interface{}, spec interface{}) *GetAvailableConcertListRepo_GetAvailableConcerts_Call {
	return &GetAvailableConcertListRepo_GetAvailableConcerts_Call{Call: _e.mock.On("GetAvailableConcerts", ctx, spec)}
}

func (_c *GetAvailableConcertListRepo_GetAvailableConcerts_Call) Run(run func(ctx context.Context, spec concert.GetAvailableSpec)) *GetAvailableConcertListRepo_GetAvailableConcerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(concert.GetAvailableSpec))
	})
	return _c
}

func (_c *GetAvailableConcertListRepo_GetAvailableConcerts_Call) Return(_a0 []concert.Concert, _a1 uint64, _a2 error) *GetAvailableConcertListRepo_GetAvailableConcerts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *GetAvailableConcertListRepo_GetAvailableConcerts_Call) RunAndReturn(run func(context.Context, concert.GetAvailableSpec) ([]concert.Concert, uint64, error)) *GetAvailableConcertListRepo_GetAvailableConcerts_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetAvailableConcertListRepo creates a new instance of GetAvailableConcertListRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAvailableConcertListRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAvailableConcertListRepo {
	mock := &GetAvailableConcertListRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
