// Code generated by mockery v2.52.3. DO NOT EDIT.

package mock_service

import (
	context "context"

	concert "github.com/iandanarko/concert/internal/model/concert"

	mock "github.com/stretchr/testify/mock"
)

// GetConcertByIDRepo is an autogenerated mock type for the GetConcertByIDRepo type
type GetConcertByIDRepo struct {
	mock.Mock
}

type GetConcertByIDRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *GetConcertByIDRepo) EXPECT() *GetConcertByIDRepo_Expecter {
	return &GetConcertByIDRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GetConcertByIDRepo) GetByID(ctx context.Context, id uint64) (*concert.Concert, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *concert.Concert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*concert.Concert, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *concert.Concert); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*concert.Concert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConcertByIDRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GetConcertByIDRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *GetConcertByIDRepo_Expecter) GetByID(ctx interface{}, id interface{}) *GetConcertByIDRepo_GetByID_Call {
	return &GetConcertByIDRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GetConcertByIDRepo_GetByID_Call) Run(run func(ctx context.Context, id uint64)) *GetConcertByIDRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *GetConcertByIDRepo_GetByID_Call) Return(_a0 *concert.Concert, _a1 error) *GetConcertByIDRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetConcertByIDRepo_GetByID_Call) RunAndReturn(run func(context.Context, uint64) (*concert.Concert, error)) *GetConcertByIDRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetConcertByIDRepo creates a new instance of GetConcertByIDRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetConcertByIDRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetConcertByIDRepo {
	mock := &GetConcertByIDRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
