definitions:
  booking.BookBodyRequest:
    properties:
      concert_id:
        type: integer
      quantity:
        type: integer
    required:
    - concert_id
    - quantity
    type: object
  serializer.ConcertResponse:
    properties:
      date:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  serializer.ListMetadata:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  serializer.MessageResponse:
    properties:
      message:
        type: string
    type: object
  serializer.SuccessMessageResponse:
    properties:
      data:
        $ref: '#/definitions/serializer.MessageResponse'
    type: object
  serializer.SuccessResponse-serializer_ConcertResponse:
    properties:
      data:
        $ref: '#/definitions/serializer.ConcertResponse'
      metadata:
        $ref: '#/definitions/serializer.ListMetadata'
    type: object
info:
  contact: {}
paths:
  /bookings:
    post:
      consumes:
      - application/json
      description: book tickets.
      parameters:
      - description: body request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/booking.BookBodyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success booking
          schema:
            $ref: '#/definitions/serializer.SuccessMessageResponse'
      security:
      - JWTAuth: []
      summary: book tickets
      tags:
      - booking
  /concerts:
    get:
      consumes:
      - application/json
      description: Retrieve available concerts list.
      parameters:
      - description: search
        in: query
        name: search
        type: string
      - description: offset
        in: query
        name: offset
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: retrieve concerts successfully
          schema:
            $ref: '#/definitions/serializer.SuccessResponse-serializer_ConcertResponse'
      security:
      - JWTAuth: []
      summary: Get Available concerts list
      tags:
      - concert
swagger: "2.0"
